### ISSUE TITLE
g++ version

### ISSUE THREAD

**Issue by KelvinYang0320** [pku-liang/TENET#2]
Hi, @wangyuyue @semiwaker what is your g++ version for TENET?
Could you provide detailed information about the environment where you build TENET and run all experiments?
I update my g++ to g++-8 to fix `filesystem: No such file or directory` but still get `terminate called after throwing an instance of 'std::bad_alloc'` after running `bin/alexnet`.
* https://stackoverflow.com/questions/39231363/fatal-error-filesystem-no-such-file-or-directory
![image](https://user-images.githubusercontent.com/49781698/209666406-5063aaca-aff7-42c4-861b-5ef05e3fe46d.png)

**Comment by semiwaker** [comment]
We used g++ 11.3.0. I think any g++ version that supports at least c++17 standard should work.

**Comment by KelvinYang0320** [comment]
@semiwaker Thank you! It seems that the g++ version >=9 works.
